schema_version = "1.0.0"
id = "atbridge"
name = "ATBridge"
version = "0.1.4"
tagline = "Automatically import asset files from Quixel Bridge"
maintainer = "Community"
type = "add-on"
tags = ["3D View", "Pipeline", "Material", "Node"]
blender_version_min = "4.3.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/BakaAkari/ATBridge"
copyright = ["2024 Baka_Akari"]
